name: Build vLLM Docker Image Matrix

env:
  PARALLELISM: 1
  TORCH_CUDA_ARCH_LIST: 9.0a
  VLLM_FA_CMAKE_GPU_ARCHES: 90a-real
  TRITON_REF: release/3.2.x
  TRITON_BUILD_SUFFIX: +cu126
  XFORMERS_REF: v0.0.29.post2
  XFORMERS_BUILD_VERSION: 0.0.29.post2+cu126
  FLASHINFER_REF: v0.2.2.post1
  FLASHINFER_BUILD_SUFFIX: cu126
  VLLM_REF: v0.8.0

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        arch: [amd64, arm64]
        cuda_version: [12.6.3]
        image_distro: [ubuntu24.04]
    runs-on: [self-hosted, "${{ matrix.arch }}"]
    steps:
      - name: Prepare some env vars
        run: |
          echo "GHCR_IMAGE=ghcr.io/${GITHUB_REPOSITORY@L}" >> ${GITHUB_ENV}
          CUDA_VERSION=${{ matrix.cuda_version }}
          CUDA_SHORT=${CUDA_VERSION%.*}
          echo "CUDA_TAG=${CUDA_SHORT//./}" >> ${GITHUB_ENV}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-config-inline: |
            [worker.oci]
              max-parallelism = ${{ env.PARALLELISM }}

      - name: Build and push builder image
        uses: docker/build-push-action@v6
        with:
          build-args: |
            CUDA_VERSION=${{ matrix.cuda_version }}
            IMAGE_DISTRO=${{ matrix.image_distro }}
            TORCH_CUDA_ARCH_LIST=${{ env.TORCH_CUDA_ARCH_LIST }}
            VLLM_FA_CMAKE_GPU_ARCHES=${{ env.VLLM_FA_CMAKE_GPU_ARCHES }}
            TRITON_REF=${{ env.TRITON_REF }}
            TRITON_BUILD_SUFFIX=${{ env.TRITON_BUILD_SUFFIX }}
            XFORMERS_REF=${{ env.XFORMERS_REF }}
            XFORMERS_BUILD_VERSION=${{ env.XFORMERS_BUILD_VERSION }}
            FLASHINFER_REF=${{ env.FLASHINFER_REF }}
            FLASHINFER_BUILD_SUFFIX=${{ env.FLASHINFER_BUILD_SUFFIX }}
            VLLM_REF=${{ env.VLLM_REF }}
          cache-from: type=registry,ref=${{ env.GHCR_IMAGE }}:cache-cu${{ env.CUDA_TAG }}-${{ matrix.arch }}
          cache-to: type=registry,ref=${{ env.GHCR_IMAGE }}:cache-cu${{ env.CUDA_TAG }}-${{ matrix.arch }},mode=max
          context: .
          file: Dockerfile
          platforms: linux/${{ matrix.arch }}
          push: true
          tags: ${{ env.GHCR_IMAGE }}:${{ env.VLLM_REF }}-cu${{ env.CUDA_TAG }}-${{ matrix.arch }}

  # Fix this to use matrix and handle imagetools create --append
  ghcr:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Prepare some env vars
        run: |
          echo "GHCR_IMAGE=ghcr.io/${GITHUB_REPOSITORY@L}" >> ${GITHUB_ENV}
          echo "CUDA_TAG=126" >> ${GITHUB_ENV}

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag images
        run: |
          TAGS=(${VLLM_REF}-cu${CUDA_TAG}-{amd,arm}64)
          docker buildx imagetools create -t ${GHCR_IMAGE}:${VLLM_REF} ${TAGS[@]/#/${GHCR_IMAGE}:}
          docker buildx imagetools create -t ${GHCR_IMAGE}:latest ${TAGS[@]/#/${GHCR_IMAGE}:}
